spring.application.name=auth-service

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security.oauth2.server.resource=DEBUG

server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/myrealm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/myrealm/protocol/openid-connect/certs


# spring.security.oauth2.client.registration.auth-service.client-id=YOUR_GOOGLE_CLIENT_ID
# spring.security.oauth2.client.registration.auth-service.client-secret=YOUR_GOOGLE_CLIENT_SECRET
# spring.security.oauth2.client.registration.auth-service.scope=openid,email,profile
# spring.security.oauth2.client.registration.auth-service.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# spring.security.oauth2.client.provider.auth-service.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
# spring.security.oauth2.client.provider.auth-service.token-uri=https://oauth2.googleapis.com/token
# spring.security.oauth2.client.provider.auth-service.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
# spring.security.oauth2.client.provider.auth-service.user-name-attribute=sub

#ssl configuration
server.ssl.enabled=true
server.ssl.key-store=classpath:backend.p12
server.ssl.key-store-password=bnt@123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=backend

# Keycloak Configuration
keycloak-info.redirect-uri=http://localhost:4200/*
keycloak-info.terminal-bst-time-zone=0
keycloak-info.url=http://localhost:8080
keycloak-info.keycloak-enable=true
keycloak-info.require-https=false
keycloak-info.skip-issuer-check=false
keycloak-info.realm=myrealm
keycloak-info.client-id=angular-app1
